#!/bin/bash
sudo yum update -y 
sudo yum install ruby-y
sudo yum install wget -y
cd /home/ec2-user
wget https://aws-codedeploy-ap-south-1.s3.ap-south-1.amazonaws.com/latest/install
sudo chmod +x ./install
sudo ./install auto
sudo yum install python-pip -y
sudo pip install awscli
